services:
    _defaults:
        autowire: true
        autoconfigure: true
            
    cloud_trace_event_dispatcher:
        class: App\EventDispatcher\CloudTraceEventDispatcher
        decorates: event_dispatcher
